CREATE DATABASE landing;
USE landing;
CREATE TABLE Leads (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(30) NOT NULL,
telefone VARCHAR(11) NOT NULL,
email VARCHAR(60),
mensagem VARCHAR(255)
);